platform :ios, ‘9.0’
inhibit_all_warnings!

def common_pods_for_target
    use_frameworks!
    pod 'ObjectMapper'
    pod 'PINRemoteImage'
    pod 'SwiftLint'
end

target 'OGloboNews' do
  common_pods_for_target
end

target 'OGloboNewsTests' do
    common_pods_for_target
end
